import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppHeader />
          <main className="container mx-auto py-10">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}

function AppHeader() {
  return (
    <header className="container mx-auto flex items-center justify-between py-5">
      <span>Instagram Clone</span>
      <nav>
        <ul className="flex gap-5">
          <Link href="/">Home</Link>
          <SignedIn>
            <SignOutButton />
          </SignedIn>
          <SignedOut>
            <SignInButton redirectUrl="/get-started" />
          </SignedOut>
        </ul>
      </nav>
    </header>
  );
}
