import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignedIn,
  SignedOut,
  currentUser,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppHeader />
          <main className="container mx-auto px-4 py-10 md:px-0">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}

function AppHeader() {
  return (
    <header className="container mx-auto flex items-center justify-between px-4 py-5 md:px-0">
      <span>Instagram Clone</span>
      <nav>
        <ul className="flex gap-5">
          <SignedIn>
            <Link href="/get-started">Profile</Link>
            <SignOutButton />
            <Link href="/create">Create</Link>
          </SignedIn>
          <SignedOut>
            <Link href="/">Home</Link>
            <SignInButton mode="modal" redirectUrl="/get-started" />
          </SignedOut>
        </ul>
      </nav>
    </header>
  );
}
